{{- if .Values.prometheus.enabled }}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "kafka.prometheus.name" . }}
  annotations:
    "helm.sh/hook-weight": "4"
  labels:
    app: {{ template "kafka.prometheus.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ template "kafka.prometheus.name" . }}
        release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kafka.prometheus.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.exporterImage }}:{{ .Values.prometheus.exporterImageTag }}"
          command: ["/bin/kafka_exporter"]
          args:
          - "--kafka.server={{ template "kafka.name" . }}:{{  .Values.port }}"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.prometheus.exporterPort }}
              name: prometheus
{{ end }}
