component: flink-connector
mandatory: false
enabled: false
port: 8080
resources:
gatewayUrl: "http://flink-jobmanager:8083"
apiCommunicationUrl: "http://api-communication/messages.send"
executor:
  name: statements-executor
  image: connectors/flink/statements-executor
  topic: flink.statements
resultSender:
  name: result-sender
  image: connectors/flink/result-sender
  topic: flink.output
