apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Airy configuration
name: prerequisites
version: 0-alpha
dependencies:
  - name: kafka
    condition: kafka.enabled
  - name: beanstalkd
    condition: beanstalkd.enabled