apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-admin
  namespace: default
  labels:
    app: api-admin
spec:
  replicas: 0
  selector:
    matchLabels:
      app: api-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-admin
    spec:
      containers:
      - name: app
        image: "{{ .Values.image }}:{{ .Values.global.appImageTag }}"
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: airy-kafka-headless:9092
        - name: KAFKA_SCHEMA_REGISTRY_URL
          value: http://airy-schema-registry:8081
        - name: FACEBOOK_APP_ID
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: FB_APP_ID
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: FB_APP_SECRET
        - name: SERVICE_NAME
          value: api-admin
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: secrets-config
              key: JWT_SECRET
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
              - name: Health-Check
                value: health-check
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3