apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.global.namespace }}
data:
  MAIL_FROM: {{ .Values.api.mailFrom }}
  MAIL_PORT: "{{ .Values.api.mailPort }}"
  MAIL_URL: {{ .Values.api.mailUrl }}
  MAIL_USERNAME: {{ .Values.api.mailUsername }}
  MAIL_PASSWORD: {{ .Values.api.mailPassword }}
  JWT_SECRET: {{ randAlphaNum 128 | quote }}
  HOST: {{ .Values.api.host }}
  ALLOWED_ORIGINS: {{ .Values.api.allowedOrigins | quote }}
