global:
  kubernetes:
    appImageTag: ${app_image_tag}
    containerRegistry: ghcr.io/airyhq
    namespace: default
    ngrokEnabled: false
    host: ${host}.${hosted_zone}
  ingress:
    nodePort: 30000
  security:
    allowedOrigins: "*"
    systemToken: "NgbjxdHuJSS3Qnv5"
    jwtSecret: "tLkdLS8e27T7cUR8eJqChDTPaNhuA2NZ"

