brokers: 0

image: confluentinc/cp-kafka
imageTag: 5.5.0

imagePullPolicy: IfNotPresent

imagePullSecrets:

podManagementPolicy: OrderedReady

updateStrategy: RollingUpdate

configurationOverrides:
  "offsets.topic.replication.factor": "2"
  "advertised.listeners": |-
    EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

customEnv:
  KAFKA_METRIC_REPORTERS: ""
  
persistence:
  enabled: true
  size: 1Gi

                
  disksPerBroker: 1

heapOptions: "-Xms512M -Xmx512M"

resources: {}
                    
podAnnotations: {}

nodeSelector: {}

tolerations: []

nodeport:
  enabled: true
  servicePort: 19092
  firstListenerPort: 31090

cp-zookeeper:
  enabled: true
  servers: 2
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi

  url: ""
