replicaCount: 1
containerRegistry: ghcr.io/airyhq
image: infrastructure/schema-registry
imageTag: 2.0.1
imagePullPolicy: Always
servicePort: 8081
kafka:
  bootstrapServers: kafka-headless:9092
  minBrokers: 1
resources:
  requests:
    cpu: "50m"  
    memory: "64Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"
