replicaCount: 1

image: confluentinc/cp-schema-registry
imageTag: 5.5.0

imagePullPolicy: IfNotPresent

imagePullSecrets:

configurationOverrides: {}

customEnv: {}

servicePort: 8081

heapOptions: "-Xms512M -Xmx512M"

kafka:
  bootstrapServers: ""

resources: {}
                    
podAnnotations: {}

nodeSelector: {}

tolerations: []

jmx:
  port: 5555

prometheus:
    jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    imagePullPolicy: IfNotPresent
    port: 5556

    resources: {}
