apiVersion: v1
kind: Service
metadata:
  name: sources-facebook-connector
  namespace: {{ .Values.global.namespace }}
  labels:
    type: spring
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: sources-facebook-connector
