apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources-google-connector
  namespace: {{ .Values.global.namespace }}
  labels:
    app: sources-google-connector
    type: sources-google
    core.airy.co/scalable: "true"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sources-google-connector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sources-google-connector
    spec:
      containers:
        - name: app
          image: '{{ .Values.global.containerRegistry}}/{{ .Values.image }}:{{ .Values.global.appImageTag }}'
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_SCHEMA_REGISTRY_URL
            - name: KAFKA_COMMIT_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_COMMIT_INTERVAL_MS
            - name: GOOGLE_SA_FILE
              valueFrom:
                configMapKeyRef:
                  name: sources-google
                  key: GOOGLE_SA_FILE
            - name: GOOGLE_PARTNER_KEY
              valueFrom:
                configMapKeyRef:
                  name: sources-google
                  key: GOOGLE_PARTNER_KEY
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
              - name: Health-Check
                value: health-check
            initialDelaySeconds: 60
        - name: ngrok
          command:
            - /bin/bash
            - -c
            - /usr/local/bin/ngrok -config=/etc/ngrok/config.yml -log=stdout -subdomain="gl-${CORE_ID}" 8080
          image: ghcr.io/airyhq/infrastructure/ngrok-client:latest
          env:
            - name: CORE_ID
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: CORE_ID
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/ngrok
              name: ngrok-client-config
      volumes:
        - name: ngrok-client-config
          configMap:
            name: ngrok-client-config
