apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources-facebook-webhook
  namespace: default
  labels:
    app: sources-facebook-webhook
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sources-facebook-webhook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sources-facebook-webhook
    spec:
      containers:
        - name: app
          image: ghcr.io/airyhq/sources/facebook-webhook:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: kafka-headless:9092
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: SERVICE_NAME
              value: sources-facebook-webhook
            - name: FB_WEBHOOK_SECRET
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: FB_WEBHOOK_SECRET
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Health-Check
                  value: health-check
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3

        - name: ngrok
          command:
            - /bin/bash
            - -c
            - /usr/local/bin/ngrok -config=/etc/ngrok/config.yml -log=stdout -subdomain="$WEBHOOK_SUBDOMAIN" 8080
          image: ghcr.io/airyhq/infrastructure/ngrok-client:latest
          env:
            - name: WEBHOOK_SUBDOMAIN
              valueFrom:
                configMapKeyRef:
                  name: public-urls
                  key: FACEBOOK_WEBHOOK_PUBLIC_URL
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/ngrok
              name: ngrok-client-config
      volumes:
        - name: ngrok-client-config
          configMap:
            name: ngrok-client-config
